secrets:
  postgres-backup_db:
    external: true
  traefik_cf-dns-api-token:
    external: true
  traefik_cf-zone-api-token:
    external: true
services:
  adminer:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.adminer_secure.middlewares=auth
      - traefik.http.routers.adminer_secure.tls.certresolver=default
  maevsi:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.maevsi_secure.tls.certresolver=default
    image: maevsi/maevsi:0.0.3@sha256:5d3ce9fafe0f0451a3c434f60f97b0fe0d9aaef1524b2793ae3a480904c0aa75
    user: (( prune ))
    volumes: (( prune ))
  portainer:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.portainer_secure.tls.certresolver=default
  postgraphile:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.postgraphile_secure.tls.certresolver=default
  postgres_backup:
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres-backup_db
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER_FILE: /run/secrets/postgres_user
    image: prodrigestivill/postgres-backup-local:12-alpine@sha256:6c5012a9740938368dc99829044e95f847525ed77ddea0bf624eb6bb88d07da8
    secrets:
    - postgres-backup_db
    - postgres_password
    - postgres_user
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    - ../production/backups/postgres/:/backups/
  traefik:
    command:
    - (( prepend ))
    - --certificatesResolvers.default.acme.email=${STACK_ACME_EMAIL}
    - --certificatesResolvers.default.acme.storage=/etc/traefik/acme/acme.json
    - --certificatesResolvers.default.acme.dnsChallenge.provider=${STACK_ACME_PROVIDER}
    deploy:
      labels:
      - (( append ))
      - traefik.http.middlewares.auth.basicauth.users=${STACK_AUTH_BASIC}
      - traefik.http.routers.traefik_secure.middlewares=auth
      - traefik.http.routers.traefik_secure.tls.certresolver=default
    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/traefik_cf-dns-api-token
      CF_ZONE_API_TOKEN_FILE: /run/secrets/traefik_cf-zone-api-token
    secrets:
    - traefik_cf-dns-api-token
    - traefik_cf-zone-api-token
  traefik_certs-dumper:
    command:
    - file
    - --clean=false
    - --crt-name="$STACK_DOMAIN"
    - --dest=/etc/traefik/acme/
    - --key-name="$STACK_DOMAIN"
    - --source=/etc/traefik/acme/acme.json
    - --version=v2
    - --watch
    environment:
      STACK_DOMAIN: ${STACK_DOMAIN}
    image: ldez/traefik-certs-dumper:v2.7.0@sha256:63614a85fe984b62716c638bca1a0a837e86f7249ef3c0e7f9db8a1fed743c96
    volumes:
    - acme_data:/etc/traefik/acme/
volumes:
  acme_data: {}
