secrets:
  postgres-backup_db:
    external: true
  # traefik_cf-api-email:
  #   external: true
  # traefik_cf-api-key:
  #   external: true
services:
  adminer:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.adminer-secure.middlewares=auth
      - traefik.http.routers.adminer-secure.tls.certresolver=default
  maevsi:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.maevsi-secure.tls.certresolver=default
    image: dargmuesli/maevsi:0.0.0
  postgraphile:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.postgraphile-secure.tls.certresolver=default
  portainer:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.portainer-secure.tls.certresolver=default
  postgres_backup:
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres-backup_db
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER_FILE: /run/secrets/postgres_user
    image: prodrigestivill/postgres-backup-local:11-alpine
    secrets:
    - postgres-backup_db
    - postgres_password
    - postgres_user
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    - ../production/backup/postgres/:/backups/
  traefik:
    command:
    - (( prepend ))
    - --certificatesResolvers.default.acme.email=${STACK_ACME_EMAIL}
    - --certificatesResolvers.default.acme.storage=/etc/traefik/acme/acme.json
    - --certificatesResolvers.default.acme.httpChallenge.entryPoint=web
    #- --acme.dnsChallenge.provider=${STACK_ACME_PROVIDER}
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.traefik-secure.middlewares=auth
      - traefik.http.routers.traefik-secure.tls.certresolver=default
    # environment:
    #   # For other providers see:
    #   # https://docs.traefik.io/configuration/acme/#provider
    #   CF_API_EMAIL_FILE: /run/secrets/traefik_cf-api-email
    #   CF_API_KEY_FILE: /run/secrets/traefik_cf-api-key
    # secrets:
    # - traefik_cf-api-email
    # - traefik_cf-api-key
  traefik_certs-dumper:
    image: ldez/traefik-certs-dumper:v2.4.0
    command:
    - file
    - --clean=false
    - --crt-name="$STACK_DOMAIN"
    - --dest=/etc/traefik/acme/
    - --key-name="$STACK_DOMAIN"
    - --post-hook=/mnt/traefik_certs-dumper/post-hook $STACK_DOMAIN
    - --source=/etc/traefik/acme/acme.json
    - --watch
    environment:
      STACK_DOMAIN: ${STACK_DOMAIN}
    volumes:
    - acme_data:/etc/traefik/acme/
    - ./configurations/traefik_certs-dumper_post-hook:/mnt/traefik_certs-dumper/post-hook
volumes:
  acme_data: {}
