name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
  push:
    branches:
      - alpha
      - beta
      - master
      - renovate/**

jobs:
  build:
    name: dargstack rgen
    uses: dargmuesli/github-actions/.github/workflows/dargstack-rgen.yml@2.1.1-beta.1
  release-semantic:
    needs: build
    name: Semantic Release
    uses: dargmuesli/github-actions/.github/workflows/release-semantic.yml@2.1.1-beta.1
    permissions:
      contents: write
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
